### PR TITLE
Doing my story about marathon runners speed

### PR DESCRIPTION
**Pull request by palrogg**
## Pull Request Checklist

Story title: This is how runners run

My pitch issue is (use the number): (none)

My story issue is (use the number): #44

### Story Issues

- [x] My pitch issue checklist is complete
- [x] My story issue checklist is complete

### Directory Format

- [x] There is a folder in `/projects/` that is my full name
- [x] Inside of that folder I have another folder just for this project

### Visualization

- [x] My visualization has a title on it
- [x] I have cited by data source on the visualization
- [x] My visualization has my name/web site/twitter handle on it (only needs **one**)
- [x] I have exported my visualization as a `png` file

### STORY.md

- [x] I have included a `STORY.md`
- [x] I have included a front matter section with the a title and summary
- [x] I have properly linked my image, with a format like ``
- [x] If necessary, I have written text and such

### Other files to include

- [x] `README.md`, linking to my data set (if possible) and giving a brief overview of how I accomplished my task
- [x] `DIARY.md`, the notes you were keeping for yourself while working on the projects (problems, solutions) 
- [x] Any IPython/Jupyter Notebook files
- [x] Any PDF files you exported along the way
- [x] Any images or other files from your process

### CODE REVIEW

**Comment by palrogg** [comment]
6 things to fix: https://travis-ci.org/jsoma/playfair-projects/builds/148736207 continuous integration is beautiful!

**Comment by jsoma** [comment]
🎉  Congratulations on being the second pull request to go green! I'll merge tomorrow in class.

**Comment by palrogg** [comment]
Great, thank you! :-) Dance

**Comment by palrogg** [comment]
It failed because of the new story. Sigh.

**Pull request merged**
